<?php

namespace ___NAMESPACE___;

/**
 *                         (!) WARNING (!)
 *
 *                  This is an autogenerated file
 *                          Do not edit it
 */


/**
 * Application model for `___TABLE___` DB table
 * This file may be autogenerated by Zazalt EntityMaker
 *
 * @author	Zazalt/EntityMaker
 * @date	___DATE___
 */
class ___CLASS___ ##extends##
{
    ##construct##

    ##members##

    ##methods##

    public function save()
    {
        
    }
}