<?php

namespace Zazalt\EntityMaker;

class EntityMaker extends \Zazalt\Databaser\Databaser
{
    private $System;
    private $exportTo;
    private $namespace;
    private $extends;
    private $constructInject;

    public function __construct()
    {
        $this->System = new \Zazalt\System\System();
    }

    public function init()
    {
        return new static();
    }

    public function setNamespace($namespace)
    {
        $this->namespace = $namespace;
        return $this;
    }

    public function setExtends($extends)
    {
        $this->extends = $extends;
        return $this;
    }

    public function setConstructInject($parameters)
    {
        $this->constructInject = $parameters;
        return $this;
    }

    public function exportTo($exportTo)
    {
        $this->exportTo = $exportTo;
        return $this;
    }

    public function run()
    {
        $entities = parent::run();

        $this->System->recursiveCreateDirectory($this->exportTo .'/AutoGenerated/Model');
        $this->System->recursiveCreateDirectory($this->exportTo .'/AutoGenerated/Repository');

        foreach($entities as $entity => $rows) {
            $this->createModel([$entity => $rows]);
        }
    }

    /**
     * Generate model file with only database raws, setters and getters
     */
    private function createModel($entity)
    {
        $autoGeneratedModelContent  =   file_get_contents(dirname(__FILE__).'/Templates/AutoGenerated/Model.php');
        $modelContent               =   file_get_contents(dirname(__FILE__).'/Templates/Model.php');
        $modelNameCamelCase         =   \Zazalt\Strink\Strink::turn(key($entity))->snakeCaseToCamelCase(true);

        $autoGeneratedModelContent = str_replace("##construct##", "protected \$modelName = '". key($entity) ."';\n\n\t##construct##", $autoGeneratedModelContent);

        $autoGeneratedModelContent = strtr($autoGeneratedModelContent, [
            '___CLASS___'       =>  $modelNameCamelCase,
            '___NAMESPACE___'   =>  $this->namespace .'\AutoGenerated\Model',
            '___TABLE___'       =>  key($entity),
            '___DATE___'        =>  date('Y-m-d H:i:s'),
            '##extends##'       =>  'extends \\'. $this->namespace .'\AutoGenerated\Repository\\'. $modelNameCamelCase,
            '##construct##'     =>  ($this->extends ? "public function __construct()\n\t{\n\t\tparent::__construct();\n\t}" : '')
        ]);

        if($this->constructInject) {
            $autoGeneratedModelContent = str_replace('__construct()', "__construct({$this->constructInject})", $autoGeneratedModelContent);
        }

        $modelContent = strtr($modelContent, [
            '___CLASS___'       =>  $modelNameCamelCase,
            '___NAMESPACE___'   =>  $this->namespace,
            '___TABLE___'       =>  key($entity),
            '___DATE___'        =>  date('Y-m-d H:i:s'),
            '##extends##'       =>  'extends \\'. $this->namespace .'\AutoGenerated\Model\\'. $modelNameCamelCase,
            '##construct##'     =>  '' //"public function __construct()\n\t{\n\t\tparent::__construct();\n\t}"
        ]);

        $members = '';
        $methods = '';
        $index = 0;
        foreach($entity as $entityName => $rows) {
            foreach($rows as $rowName => $row) {
                $members .= ($index > 0 ? "\n" : null);
                $members .= "\n\t/**";
                $members .= "\n\t* @rowName\t\t". $rowName;
                //$members .= "\n\t* @nullable\t\t{$entity['is_nullable']}";
                $members .= "\n\t* @primaryKey\t". (boolval($row['primaryKey']) ? 'true' : 'false');
                $members .= "\n\t* @type\t\t\t{$row['type']}";
                $members .= "\n\t* @default\t\t{$row['default']}";
                $members .= "\n\t*/";
                $members .= "\n\t";
                $members .= 'private $'. \Zazalt\Strink\Strink::turn($rowName)->snakeCaseToCamelCase(false) .';';
                ++$index;
            }

            foreach($rows as $rowName => $row) {
                $rowNameCamelCase       = \Zazalt\Strink\Strink::turn($rowName)->snakeCaseToCamelCase(false);
                $rowNameUcfCamelCase    = \Zazalt\Strink\Strink::turn($rowName)->snakeCaseToCamelCase(true);

                $methods .= "\n\n\tpublic function set". $rowNameUcfCamelCase ."(\${$rowNameCamelCase})\n\t{\n\t\t\$this->{$rowNameCamelCase} = \${$rowNameCamelCase};\n\t\treturn \$this;\n\t}";
                $methods .= "\n\n\tpublic function get". $rowNameUcfCamelCase ."()\n\t{\n\t\treturn \$this->{$rowNameCamelCase};\n\t}";
            }
        }

        $autoGeneratedModelContent = str_replace('##members##', $members, $autoGeneratedModelContent);
        $autoGeneratedModelContent = str_replace('##methods##', $methods, $autoGeneratedModelContent);

        file_put_contents($this->exportTo ."/AutoGenerated/Model/{$modelNameCamelCase}.php", $autoGeneratedModelContent);

        $modelPath = $this->exportTo ."/{$modelNameCamelCase}.php";
        if(!file_exists($modelPath)) {
            file_put_contents($this->exportTo ."/{$modelNameCamelCase}.php", $modelContent);
        }

        $this->createRepository(
            $entity,
            \Zazalt\Strink\Strink::turn(key($entity))->snakeCaseToCamelCase(true)
        );
    }

    /**
     * Generate repository file with some utility functions
     */
    private function createRepository($entity, $modelNameCamelCase)
    {
        $fileContent    =   file_get_contents(dirname(__FILE__).'/Templates/Repository.php');

        $fileContent   = strtr($fileContent, [
            '___CLASS___'       =>  $modelNameCamelCase,
            '___NAMESPACE___'   =>  $this->namespace .'\AutoGenerated\Repository',
            '___TABLE___'       =>  key($entity),
            '___DATE___'        =>  date('Y-m-d H:i:s'),
            '##extends##'       =>  ($this->extends ? 'extends '. $this->extends : ''),
            '##construct##'     =>  ($this->extends ? "public function __construct()\n\t{\n\t\tparent::__construct();\n\t}" : '')
        ]);

        if($this->constructInject) {
            $fileContent = str_replace('__construct()', "__construct({$this->constructInject})", $fileContent);
        }

        file_put_contents($this->exportTo ."/AutoGenerated/Repository/{$modelNameCamelCase}.php", $fileContent);
    }
}